[tool.poetry]
name = "sistema-monitoreo-apollo-11"
version = "0.1.0"
description = ""
authors = ["Grupo 40"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
